### ISSUE TITLE
cannot execute python script

### ISSUE THREAD

**Issue by JD154** [seamus-45/roficlip#1]
I'm trying to use your script but I get the following error during executing:

![screen2017-02-03-18 48 25](https://cloud.githubusercontent.com/assets/16437806/22611569/ae687dca-ea41-11e6-9d56-44a2e3c3de91.jpg)

I have already symlinked and made chmod +x the .py

Thank you!

**Comment by seamus-45** [comment]
Sorry for late answer, I found that the project notifications were disabled.
What version of pynotify is installed?
You can also just disable notifications in settings since #2 

Also note that the required version of python is 2.7 I have not test it with 3+

**Comment by seamus-45** [comment]
Closed due to inactivity.
