### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by stef204** [seamus-45/roficlip#3]
when running:
`rofi -modi "clipboard:roficlip.py --show,persistent:roficlip.py --show --persistent,actions:roficlip.py --show --actions" -show clipboard`

result:
`% Traceback (most recent call last):
  File "/home/user/bin/roficlip.py", line 108, in fifo_watcher
    self.notify_send('Copied to the clipboard.')
  File "/home/user/bin/roficlip.py", line 180, in notify_send
    n = pynotify.Notification("Roficlip", text)
NameError: global name 'pynotify' is not defined`

Installed: python2-notify 0.1.1-13 and libnotify 0.7.7-1

Is this what I need perhaps: python2-notify2 from [here](https://pypi.python.org/pypi/notify2/)?

**Comment by seamus-45** [comment]
@stef204 
Seems previous PR was not correct. Please check again from the master.
