### ISSUE TITLE
Can roficlip show both primary and clipboard?

### ISSUE THREAD

**Issue by stef204** [seamus-45/roficlip#4]
Seems to only show primary.  can it be made to show both primary and clipboard?

Also, is there a guide as to use to yaml config file? All of the parameters/options possible?  (I may have missed that.)

Thanks.

**Comment by seamus-45** [comment]
>Seems to only show primary. 

According to docs default selection for [gtk.Clipboard](http://www.pygtk.org/pygtk2reference/class-gtkclipboard.html) is "CLIPBOARD". This is exactly what is used in roficlip.

>can it be made to show both primary and clipboard?

You are welcome to implement such thing. Im not plan this feature. 

>Also, is there a guide as to use to yaml config file? All of the parameters/options possible?

Full example of config file was described in README.md

**Comment by stef204** [comment]
Sorry, I had it inverted in my original post: I meant "...only shows CLIPBOARD but not PRIMARY", and can it be made to show both.

Re. yaml settings, I thought there might be more options possible.
If not, yes, everything is in README.

Thanks.
